INSERT INTO Clothings(Name, Description, Category, Price)
VALUES 

('Snickerhead kittens black',	'Fresh drop for all sneaker lovers! Quantity is limited 100% cotton',	't-shirt',	2290),
('Snickerhead kittens white',	'Fresh drop for all sneaker lovers! Quantity is limited 100% cotton'	,'t-shirt',	2290),
('Satan kitties',	'comfortable, pleasant to the touch cool thing 100% cotton',	't-shirt',	2290),
('Beer club kittens black',	'The final stage of pre-order for the club of beer kittens! Grab yourself a legendary item! 100% cotton',	't-shirt',	2190),
('Beer club kittens white',	'The final stage of pre-order for the club of beer kittens! Grab yourself a legendary item! 100% cotton',	't-shirt',	2190),
('Types of kittens', 'Knowing the types of kittens is a quality that is greatly appreciated both in the working environment and in everyday life. And putting ona cheat sheet with types of kittens is not only a useful, but also a stylish solution.',	't-shirt',	2190),
('Types of fossils',	'comfortable, pleasant to the touch cool thing - remember them all! 100% cotton',	't-shirt',	2190),
('Snickerhead kittens black',	'Fresh drop for all sneaker lovers! Quantity is limited 100% cotton',	'hoodie',	3390),
('Snickerhead kittens beige',	'Fresh drop for all sneaker lovers! Quantity is limited 100% cotton',	'hoodie',	3390),
('Satan kitties',	'comfortable, pleasant to the touch cool thing 100% cotton',	'hoodie',	3290),
('Beer club kittens black',	'The final stage of pre-order for the club of beer kittens! Grab yourself a legendary item! 100% cotton',	'hoodie',	3290),
('Types of kittens',	'Knowing the types of kittens is a quality that is greatly appreciated both in the working environment and in everyday life. And putting ona cheat sheet with types of kittens is not only a useful, but also a stylish solution.',	'hoodie'	,3290),
('Types of fossils',	'comfortable, pleasant to the touch cool thing - remember them all! 100% cotton',	'hoodie',	3290),
('Pink kittens vest',	'50% cotton, 50% acrylic, oversized fit',	'vests',	3290),
('Beige kittens vest',	'50% cotton, 50% acrylic, oversized fit',	'vests',	3290),
('Black kittens vest',	'50% cotton, 50% acrylic, oversized fit',	'vests',	3290),
('Pink fleece',	'This is a fleece, which means the composition is 100% fleece On the chest is the daddy cassette that you found under the sofa. Cozier than warm tea and biscuits',	'fleece',	2990),
('Beige fleece', 'This is a fleece, which means the composition is 100% fleece On the chest is the daddy cassette that you found under the sofa. Cozier than warm tea and biscuits',	'fleece',	2990),
('Plants cap',	'Mydriasis Adult Entertainment',	'caps',	2290),
('Milf cap',	'Mydriasis Adult Entertainment',	'caps',	2290),
('4:20 bag',	'Mydriasis Adult Entertainment',	'bags',	2690),
('White necklace',	'white necklace with natural amethysts',	'neckless',	490),
('Colored necklace',	'colored necklace with natural amethysts',	'neckless',	490),
('choker on a velvet ribbon with a tooth',	'choker on a velvet ribbon with a tooth length adjustable by chain at the back',	'neckless',	590),
('choker on a pink ribbon with an angel',	'choker on a pink ribbon with an angel length adjustable by chain at the back',	'neckless',	590),
('choker on a black ribbon with an angel',	'choker on a black ribbon with an angel length adjustable by chain at the back',	'neckless',	590)
